### ISSUE TITLE
Can I access to your roboflow manga109 dataset, I want to train the model based on the Yolo v8 model?

### ISSUE THREAD

**Issue by jojogh** [simon-caignart/yolor-manga-text-detection#1]
Can I access to your roboflow manga109 dataset, I want to train the model based on the Yolo v8 model?

**Comment by simon-caignart** [comment]
Hey @jojogh. Unfortunately I don't have the roboflow dataset anymore. You can send an application via [this form](https://docs.google.com/forms/d/e/1FAIpQLSefUGHUlkDfYlnOKLZlBqRtqlhmZWmhL1_NBfZ24zHOeCoguA/viewform) to download the dataset and create your own roboflow project.

**Comment by jojogh** [comment]
many thanks!
